# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Create release on commit to master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: shadowJar
    - name: Set tag
      id: tag
      run: echo ::set-output name=version_tag::./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'
    - name: Create release
      uses: softprops/action-gh-release@v0.1.14
      with:
        tag_name: ${{ steps.tag.outputs.version_tag }}
        files: build/libs/*.jar
